### ISSUE TITLE
Замена массивов на коллекции

### ISSUE THREAD

**Issue by ILGO0413** [sergeymacrushin/financiAlassistent11#1]
https://github.com/sergeymacrushin/financiAlassistent11/blob/0f13f044362edd33c3d5dff4ff59b141a354eb69/src/com/company/Balance.java#L4
Java предоставляет коллекции - хранилище данных динамического размера. Рекомендую ознакомиться и попробовать заменить массивы на коллекции.

**Comment by sergeymacrushin** [comment]
ок
